# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
    parallelism: 1

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        - v1-dependencies-
    - run: ./gradlew dependencies
    - save_cache:
        paths:
        - ~/.gradle
        - ~/repo/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}
    - run: ./gradlew test
    - store_test_results:
        path: build/test-results/
